### ISSUE TITLE
Updates TODO

### ISSUE THREAD

**Issue by wolffha** [hendriau/Summix#1]
The following updates need to be made:

- [ ] summix() function update for slsqp package compatibility (current features used will be discontinued)
- [x] warning messages for summix_local update (regarding override options)

**Comment by wolffha** [comment]
- [x] summix_local() remove blocks that have all observed AF = 0

**Comment by wolffha** [comment]
- [x] Summix local default p-value -> cauchy correction test
- [x] calc_scaledobj: add in data <- data[complete.cases(data), ] after binning

**Comment by Adelleprice1** [comment]
Calculate goodness of fit by first converting to MAF
